version: "3.9"
services:
  db:
    image: postgres:14.3-alpine
    ports:
      - "5454:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}